In [ ]:
#Question 1
# website: https://books.toscrape.com/index.html 
# I first tried TGNA documents from tbmm.gov.tr, but it was very complex for me to understand and I get error in the first steps. 
# then I tried WorldBank and IMDB, but in the "len(sel.xpath(xpath_for_titles).extract())" step it returned "0" so there was no titles. 
# Therefore, I looked into the dummy websites for scraping so that I can do the assignment. I find this website online. 
# This website is public, include the book names and prices under different categories. I tried to subtract a single category.

In [1]:
# Question 2
from scrapy import Selector

In [2]:
import requests

In [3]:
url = 'https://books.toscrape.com/index.html'

In [5]:
html = requests.get(url).content

sel = Selector(text = html)

In [7]:
print(len(sel.xpath('//*')))

541

In [8]:
html

b'<!DOCTYPE html>\n<!--[if lt IE 7]>      <html lang="en-us" class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->\n<!--[if IE 7]>         <html lang="en-us" class="no-js lt-ie9 lt-ie8"> <![endif]-->\n<!--[if IE 8]>         <html lang="en-us" class="no-js lt-ie9"> <![endif]-->\n<!--[if gt IE 8]><!--> <html lang="en-us" class="no-js"> <!--<![endif]-->\n    <head>\n        <title>\n    All products | Books to Scrape - Sandbox\n</title>\n\n        <meta http-equiv="content-type" content="text/html; charset=UTF-8" />\n        <meta name="created" content="24th Jun 2016 09:29" />\n        <meta name="description" content="" />\n        <meta name="viewport" content="width=device-width" />\n        <meta name="robots" content="NOARCHIVE,NOCACHE" />\n\n        <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->\n        <!--[if lt IE 9]>\n        <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>\n        <![endif]-->\n\n        \n            <link rel="shortcut icon" href="static/oscar/favicon.ico" />\n        \n\n        \n        \n    \n    \n        <link rel="stylesheet" type="text/css" href="static/oscar/css/styles.css" />\n    \n    <link rel="stylesheet" href="static/oscar/js/bootstrap-datetimepicker/bootstrap-datetimepicker.css" />\n    <link rel="stylesheet" type="text/css" href="static/oscar/css/datetimepicker.css" />\n\n\n        \n        \n\n        \n\n        \n            \n            \n\n        \n    </head>\n\n    <body id="default" class="default">\n        \n        \n    \n    \n    <header class="header container-fluid">\n        <div class="page_inner">\n            <div class="row">\n                <div class="col-sm-8 h1"><a href="index.html">Books to Scrape</a><small> We love being scraped!</small>\n</div>\n\n                \n            </div>\n        </div>\n    </header>\n\n    \n    \n<div class="container-fluid page">\n    <div class="page_inner">\n        \n    <ul class="breadcrumb">\n        <li>\n            <a href="index.html">Home</a>\n        </li>\n        <li class="active">All products</li>\n    </ul>\n\n        <div class="row">\n\n            <aside class="sidebar col-sm-4 col-md-3">\n                \n                <div id="promotions_left">\n                    \n                </div>\n                \n    \n    \n        \n        <div class="side_categories">\n            <ul class="nav nav-list">\n                \n                    <li>\n                        <a href="catalogue/category/books_1/index.html">\n                            \n                                Books\n                            \n                        </a>\n\n                        <ul>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/travel_2/index.html">\n                            \n                                Travel\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/mystery_3/index.html">\n                            \n                                Mystery\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/historical-fiction_4/index.html">\n                            \n                                Historical Fiction\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/sequential-art_5/index.html">\n                            \n                                Sequential Art\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/classics_6/index.html">\n                            \n                                Classics\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/philosophy_7/index.html">\n                            \n                                Philosophy\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/romance_8/index.html">\n                            \n                                Romance\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/womens-fiction_9/index.html">\n                            \n                                Womens Fiction\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/fiction_10/index.html">\n                            \n                                Fiction\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/childrens_11/index.html">\n                            \n                                Childrens\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/religion_12/index.html">\n                            \n                                Religion\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/nonfiction_13/index.html">\n                            \n                                Nonfiction\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/music_14/index.html">\n                            \n                                Music\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/default_15/index.html">\n                            \n                                Default\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/science-fiction_16/index.html">\n                            \n                                Science Fiction\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/sports-and-games_17/index.html">\n                            \n                                Sports and Games\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/add-a-comment_18/index.html">\n                            \n                                Add a comment\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/fantasy_19/index.html">\n                            \n                                Fantasy\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/new-adult_20/index.html">\n                            \n                                New Adult\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/young-adult_21/index.html">\n                            \n                                Young Adult\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/science_22/index.html">\n                            \n                                Science\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/poetry_23/index.html">\n                            \n                                Poetry\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/paranormal_24/index.html">\n                            \n                                Paranormal\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/art_25/index.html">\n                            \n                                Art\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/psychology_26/index.html">\n                            \n                                Psychology\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/autobiography_27/index.html">\n                            \n                                Autobiography\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/parenting_28/index.html">\n                            \n                                Parenting\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/adult-fiction_29/index.html">\n                            \n                                Adult Fiction\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/humor_30/index.html">\n                            \n                                Humor\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/horror_31/index.html">\n                            \n                                Horror\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/history_32/index.html">\n                            \n                                History\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/food-and-drink_33/index.html">\n                            \n                                Food and Drink\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/christian-fiction_34/index.html">\n                            \n                                Christian Fiction\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/business_35/index.html">\n                            \n                                Business\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/biography_36/index.html">\n                            \n                                Biography\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/thriller_37/index.html">\n                            \n                                Thriller\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/contemporary_38/index.html">\n                            \n                                Contemporary\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/spirituality_39/index.html">\n                            \n                                Spirituality\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/academic_40/index.html">\n                            \n                                Academic\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/self-help_41/index.html">\n                            \n                                Self Help\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/historical_42/index.html">\n                            \n                                Historical\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/christian_43/index.html">\n                            \n                                Christian\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/suspense_44/index.html">\n                            \n                                Suspense\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/short-stories_45/index.html">\n                            \n                                Short Stories\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/novels_46/index.html">\n                            \n                                Novels\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/health_47/index.html">\n                            \n                                Health\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/politics_48/index.html">\n                            \n                                Politics\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/cultural_49/index.html">\n                            \n                                Cultural\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/erotica_50/index.html">\n                            \n                                Erotica\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/crime_51/index.html">\n                            \n                                Crime\n                            \n                        </a>\n\n                        </li>\n                        \n                            </ul></li>\n                        \n                \n            </ul>\n        </div>\n    \n    \n\n            </aside>\n\n            <div class="col-sm-8 col-md-9">\n                \n                <div class="page-header action">\n                    <h1>All products</h1>\n                </div>\n                \n\n                \n\n\n\n<div id="messages">\n\n</div>\n\n\n                <div id="promotions">\n                    \n                </div>\n\n                \n    <form method="get" class="form-horizontal">\n        \n        <div style="display:none">\n            \n            \n        </div>\n\n        \n            \n                \n                    <strong>1000</strong> results - showing <strong>1</strong> to <strong>20</strong>.\n                \n            \n            \n        \n    </form>\n    \n        <section>\n            <div class="alert alert-warning" role="alert"><strong>Warning!</strong> This is a demo website for web scraping purposes. Prices and ratings here were randomly assigned and have no real meaning.</div>\n\n            <div>\n                <ol class="row">\n                    \n             

In [9]:
type(html)

bytes

In [10]:
type(sel)

scrapy.selector.unified.Selector

In [63]:
# Question 3 but I think data extraction starts with request command, I got confused in some parts.
from scrapy import Selector

url = "https://books.toscrape.com/index.html"
response = requests.get(url)

In [64]:
print(response.status_code)

200

In [65]:
sel = Selector(text=response.text)

In [99]:
# from the classnotes, some online resources and chatgbt I understand how xpath works, but I needed to get help a lot. 

my_titles = sel.xpath('//h3/a/@title').getall()
print(my_titles)
my_prices = sel.css('p.price_color::text').getall()

['A Light in the Attic', 'Tipping the Velvet', 'Soumission', 'Sharp Objects', 'Sapiens: A Brief History of Humankind', 'The Requiem Red', 'The Dirty Little Secrets of Getting Your Dream Job', 'The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull', 'The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics', 'The Black Maria', 'Starving Hearts (Triangular Trade Trilogy, #1)', "Shakespeare's Sonnets", 'Set Me Free', "Scott Pilgrim's Precious Little Life (Scott Pilgrim #1)", 'Rip it Up and Start Again', 'Our Band Could Be Your Life: Scenes from the American Indie Underground, 1981-1991', 'Olio', 'Mesaerion: The Best Science Fiction Stories 1800-1849', 'Libertarianism for Beginners', "It's Only the Himalayas"]

In [100]:
# This I copied from the classnotes. 
import re

def strip_tags(html):
    clean = re.compile('<.*?>')
    return re.sub(clean, '', html)

cleaned_strings = [strip_tags(html) for html in titles]

print(cleaned_strings)

['A Light in the Attic', 'Tipping the Velvet', 'Soumission', 'Sharp Objects', 'Sapiens: A Brief History of Humankind', 'The Requiem Red', 'The Dirty Little Secrets of Getting Your Dream Job', 'The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull', 'The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics', 'The Black Maria', 'Starving Hearts (Triangular Trade Trilogy, #1)', "Shakespeare's Sonnets", 'Set Me Free', "Scott Pilgrim's Precious Little Life (Scott Pilgrim #1)", 'Rip it Up and Start Again', 'Our Band Could Be Your Life: Scenes from the American Indie Underground, 1981-1991', 'Olio', 'Mesaerion: The Best Science Fiction Stories 1800-1849', 'Libertarianism for Beginners', "It's Only the Himalayas"]

In [101]:
df = pd.read_csv('books_cleaned.csv')

df.head(10)

,category,title,price,availability
0,Travel,It's Only the Himalayas,NaN,In stock
1,Travel,Full Moon over Noahâs Ark: An Odyssey to Mou...,NaN,In stock
2,Travel,See America: A Celebration of Our National Par...,NaN,In stock
3,Travel,Vagabonding: An Uncommon Guide to the Art of L...,NaN,In stock
4,Travel,Under the Tuscan Sun,NaN,In stock
5,Travel,A Summer In Europe,NaN,In stock
6,Travel,The Great Railway Bazaar,NaN,In stock
7,Travel,A Year in Provence (Provence #1),NaN,In stock
8,Travel,The Road to Little Dribbling: Adventures of an...,NaN,In stock
9,Travel,Neither Here nor There: Travels in Europe,NaN,In stock

In [102]:
#Question 4--Data cleaning
prices = []
for p in my_prices:
    p = p.replace("£", "").replace("Â", "").strip()
    prices.append(float(p) if p else None)

In [105]:
#Question 5--DATA Storage

df = pd.DataFrame({
    "title": titles,
    "price": prices,
    "rating": raw_ratings,
    "availability": availability
})

print(df.head())

                                   title  price rating availability
0                   A Light in the Attic  51.77  Three     In stock
1                     Tipping the Velvet  53.74    One     In stock
2                             Soumission  50.10    One     In stock
3                          Sharp Objects  47.82   Four     In stock
4  Sapiens: A Brief History of Humankind  54.23   Five     In stock

In [106]:
df.head()

                                   title  price rating availability
0                   A Light in the Attic  51.77  Three     In stock
1                     Tipping the Velvet  53.74    One     In stock
2                             Soumission  50.10    One     In stock
3                          Sharp Objects  47.82   Four     In stock
4  Sapiens: A Brief History of Humankind  54.23   Five     In stock