In [1]:
from lxml import etree
import pandas as pd

In [2]:
ENV_KEYWORDS = {
    "extractivism": [
        "madencilik", "maden", "altın madeni", "taş ocağı","kömür", "linyit", 
        "rezerv", "ruhsat", "altın"
    ],

    "energy_projects": [
         "hes", "hidroelektrik", "termik", "nükleer", "rüzgar", "güneş", "enerji yatırımı",
    ],

    "developmentalist": [
        "kalkınma", "yatırım", "istihdam", "milli ekonomi", "milletimizin refahı",
        "dışa bağımlılık",
    ],

    "sustainability": [
        "çevre", "doğa", "ekosistem",
        "biyoçeşitlilik", "iklim değişikliği",
        "sürdürülebilirlik", "politika yapıcılar",
        "karbon", "emisyon"
    ],

    "environmental_justice": [
        "çevre adaleti", "yaşam alanı",
        "yerel halk", "hak mücadelesi", "direniş",
    ]
}

In [3]:
import re

def clean_whitespace(text):
    text = re.sub(r"\s+", " ", text)
    return text.strip()

In [4]:
NS = {
    "tei": "http://www.tei-c.org/ns/1.0",
    "xi": "http://www.w3.org/2001/XInclude"
}

In [5]:
parser = etree.XMLParser(remove_blank_text=True)
tree = etree.parse(PARLAMINT_FILE, parser)
root = tree.getroot()

NameError: name 'PARLAMINT_FILE' is not defined

In [6]:
import glob

BASE_DIR = "ParlaMint-TR.ana/ParlaMint-TR.TEI.ana/"

tei_files = [
    f for f in glob.glob(BASE_DIR + "**/*.xml", recursive=True)
    if (
        "taxonomy" not in f.lower()
        and "list" not in f.lower()
        and "ParlaMint-TR_" in f
    )
]

len(tei_files)

1335

In [7]:
tei_files[:5]
# 1335 oturum

['ParlaMint-TR.ana/ParlaMint-TR.TEI.ana/2013/ParlaMint-TR_2013-05-23-tbmm-T24.ana.xml',
 'ParlaMint-TR.ana/ParlaMint-TR.TEI.ana/2013/ParlaMint-TR_2013-03-19-tbmm-T24.ana.xml',
 'ParlaMint-TR.ana/ParlaMint-TR.TEI.ana/2013/ParlaMint-TR_2013-11-07-tbmm-T24.ana.xml',
 'ParlaMint-TR.ana/ParlaMint-TR.TEI.ana/2013/ParlaMint-TR_2013-03-27-tbmm-T24.ana.xml',
 'ParlaMint-TR.ana/ParlaMint-TR.TEI.ana/2013/ParlaMint-TR_2013-02-06-tbmm-T24.ana.xml']

In [8]:
test_file = tei_files[0]
print("Testing:", test_file)

tree = etree.parse(test_file)
root = tree.getroot()

speeches = []

for u in root.xpath(".//tei:u", namespaces=NS):
    text = " ".join(u.xpath(".//text()", namespaces=NS)).strip()
    if text:
        speeches.append(text)

len(speeches)

Testing: ParlaMint-TR.ana/ParlaMint-TR.TEI.ana/2013/ParlaMint-TR_2013-05-23-tbmm-T24.ana.xml

766

In [9]:
speeches[:2]

['Sayın \n milletvekilleri \n , \n                      \n Türkiye \n Büyük \n Millet \n Meclisinin \n                      \n 109’uncu \n Birleşimini \n açıyorum \n . \n \n \n \n \n \n \n \n \n \n \n \n \n \n                   \n                \n                \n                   \n                      \n                      \n Elektronik \n                      \n cihazla \n yoklama \n yapacağız \n . \n \n \n \n \n \n \n \n                   \n                \n                \n                   \n                      \n Yoklama \n için \n                      \n üç \n dakika \n                      \n süre \n veriyorum \n . \n \n \n \n \n \n \n \n \n \n                   \n                \n                Elektronik cihazla yoklama yapıldı \n                \n                   \n                      \n Toplantı \n yeter \n sayısı \n var \n dır \n , \n görüşmelere \n başlıyoruz \n . \n \n \n \n \n \n \n \n \n \n \n \n                   \n                \n                \n                   \n                      \n Gündeme \n geçmeden \n önce \n üç \n sayın \n                      \n milletvekiline \n                      \n gündem \n dışı \n söz \n vereceğim \n . \n \n \n \n \n \n \n \n \n \n \n \n \n \n                   \n                \n                \n                   \n                      \n Gündem \n dışı \n ilk \n söz \n , \n                      \n Kanal \n İstanbul’un \n                      \n çevreye \n etkileri \n hakkında \n söz \n isteyen \n                      \n İstanbul \n                      \n Milletvekili \n                      \n Haluk \n Eyidoğan’a \n                      \n ait \n tir \n . \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n                   \n                \n                \n                   \n                      \n Buyurun \n                      \n Sayın \n Eyidoğan \n                      \n .',
 'Sayın \n Başkan \n , \n değer \n li \n milletvekilleri \n ; \n son \n birkaç \n yıldır \n zaman \n zaman \n gündeme \n gelen \n ve \n bilimsel \n liği \n çok \n tartışılan \n bir \n projeden \n bahsedeceğiz \n ; \n İstanbul’u \n ilgilendiren \n , \n                      \n Marmara \n Denizi \n                      \n ve \n                      \n Karadeniz’i \n                      \n ilgilendiren \n bir \n proje \n , \n ‘ \n                      \n Kanal \n İstanbul \n                      \n ’ \n . \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n                   \n                   \n                      \n                      \n Sayın \n Başbakan \n                      \n bu \n projeyi \n ortaya \n attı \n , \n “ \n                      \n Kanal \n İstanbul \n                      \n ” \n dendi \n , \n bir \n ara \n çılgın \n projelerden \n biri \n olarak \n “ \n Çılgın \n Proje \n ” \n dendi \n . \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n                   \n                   \n                      \n Bu \n projeyle \n ilgi \n li \n Sayın \n                      \n Ali \n Babacan \n                      \n şöyle \n diyor \n : \n “ \n İlk \n etapta \n bakanlar \n olarak \n ‘ \n Acaba \n olur \n mu \n , \n olmaz \n mı \n ? \n ’ \n ‘ \n Çok \n mu \n çılgın \n ? \n ’ \n ‘ \n Acaba \n gerçekleşebilir \n mi \n ? \n ’ \n şeklinde \n şüpheler \n hissettik \n ama \n Sayın \n Başbakanımız \n bunu \n açıkladı \n , \n olmayacak \n olsa \n zaten \n bu \n açıklanmazdı \n . \n ” \n diyor \n . \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n                   \n                   \n                      \n Demek \n ki \n proje \n tamamen \n afaki \n , \n imaj \n projesi \n , \n hiçbir \n bilimsel \n çalışmaya \n dayanmıyor \n ; \n animasyon \n var \n , \n bilim \n yok \n . \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n                   \n                \n                \n                   \n                      \n Geçenlerde \n cevap \n alamadığım \n ız \n soru \n önergesini \n burada \n herke \n                      \n sin \n                      \n önünde \n okudum \n , \n hâlâ \n cevap \n alamadık \n bu \n soru \n önergesine \n . \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n                   \n                   \n                      \n Ama \n , \n Başbakan \n , \n bu \n bilimsel \n liği \n bilinmeyen \n projeyi \n                      \n Yüksek \n Planlama \n Kurulundan \n                      \n geçirdi \n . \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n                   \n                   \n                      \n                      \n Sayın \n Babacan \n                      \n diyor \n ki \n : \n “ \n Her \n türlü \n çevre \n değerlendirmesi \n ve \n hazırlığı \n çok \n dikkat \n li \n yapılmalı \n . \n ” \n Yani \n anlaşılan \n , \n istim \n arkadan \n gelecek \n . \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n                   \n                \n                \n                   \n                      \n                      \n Kanal \n İstanbul \n Projesi’nin \n                      \n hazırlık \n çalışmaları \n süresince \n , \n denizlerimizde \n yıl \n lardır \n çalışan \n değer \n li \n deniz \n bilimcilerimizin \n görüşü \n sorulmamıştır \n . \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n                   \n                   \n                      \n Sayın \n milletvekilleri \n , \n bizim \n bilim \n insanlarımızın \n hesap \n ve \n modellemelerine \n göre \n , \n bu \n proje \n nedeniyle \n beklenen \n çevresel \n felaketler \n hem \n                      \n Marmara \n                      \n hem \n de \n                      \n Karadeniz’de \n                      \n olacaktır \n . \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n                   \n                   \n                      \n Ben \n bu \n konuşmanın \n içeriğinde \n , \n yalnız \n denizlerimize \n etki \n açısından \n ele \n alıyorum \n ; \n bunun \n karada \n ve \n diğer \n çevre \n etkileri \n konusu \n ve \n inşaatla \n ilgi \n li \n konusu \n ayrı \n bir \n konuşma \n konusu \n dur \n . \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n                   \n                \n                \n                   \n                      \n                      \n İstanbul \n Boğazı \n                      \n , \n                      \n Karadeniz’in \n                      \n alt \n tuz \n lu \n sularını \n                      \n Marmara’ya \n                      \n ulaştıran \n bir \n su \n yolu \n dur \n , \n hatta \n                      \n Çanakkale \n Boğazı \n                      \n yoluyla \n                      \n Ege’ye \n                      \n de \n gider \n . \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n                   \n                   \n                      \n Nedeni \n , \n yoğun \n tatlı \n su \n deposu \n olan \n                      \n Karadeniz’in \n                      \n ortalama \n su \n seviyesinin \n Akdeniz’e \n göre \n daha \n yüksek \n olması \n dır \n . \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n                   \n                   \n                      \n                      \n Karadeniz \n suyu \n                      \n Boğaz’ın \n üstünden \n akar \n , \n alt \n tarafından \n da \n ters \n yönde \n akan \n Akdeniz’in \n tuz \n lu \n suları \n Karadeniz’in \n tuz \n dengesini \n sağlar \n . \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n                   \n                   \n                      \n Bu \n , \n eşi \n benzeri \n olmayan \n doğal \n bir \n akışkan \n                      \n lar \n                      \n mekanizması \n dır \n . \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n                   \n                   \n                      \n Boğaz’ın \n doğal \n alt \n - \n üst \n akıntı \n sistemi \n olmasaydı \n , \n                      \n Marmara \n Denizi \n                      \n bugün \n                      \n künden \n                      \n daha \n beter \n bir \n açık \n kanalizasyona \n dönüşmüş \n olacaktı \n . \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n                   \n                \n                \n                   \n                      \n Bu \n proje \n , \n                      \n Süveyş \n Kana \n lı \n                      \n ve \n                      \n Panama \n Kanalı’yla \n                      \n karşılaştırılamaz \n . \n \n \n \n \n \n \n \n \n \n \n \n \n \n                   \n                   \n                      \n Bu \n karşılaştırmayı \n yapmak \n , \n bilimden \n uzak \n durmak \n demek \n tir \n . \n \n \n \n \n \n \n \n \n \n \n \n \n                   \n                \n                \n                   \n                      \n Gerek \n li \n incelemeler \n yapılmadan \n açılacak \n olan \n bu \n çılgın \n kanalın \n geri \n dönüşü \n olmayacaktır \n . \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n                   \n                   \n                      \n Kanalın \n çevreye \n etkileri \n gelecek \n                      \n nesiller \n                      \n düşünülerek \n incelenmelidir \n . \n \n \n \n \n \n \n \n \n \n \n                   \n                   \n                      \n Ama \n                      \n Planlama \n Kurulu \n                      \n karar \n vermiş \n , \n neye \n göre \n olduğu \n belli \n değil \n dir \n . \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n                   \n                \n                \n                   \n                      \n                      \n Karadeniz’i \n                      \n dolduran \n musluklar \n yağmur \n ve \n nehir \n suları \n dır \n . \n \n \n \n \n \n \n \n \n \n \n \n                   \n                   \n                      \n Bunların \n başında \n da \n                      \n Tuna \n                      \n , \n                      \n Dinyeper \n                      \n , \n                      \n Dinyester \n                      \n ve \n                      \n Don \n                      \n nehirleri \n gelir \n . \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n                   \n                   \n                      \n Bu \n havuza \n giren \n suların \n miktarını \n artırmadan \n                      \n Karadeniz’e \n                      \n bir \n yapay \n kanal \n açarsanız \n Karadeniz’in \n suyu \n daha \n fazla \n boşalır \n . \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n                   \n                   \n                      \n Zaman \n içerisinde \n                      \n Karadeniz’in \n                      \n alt \n tabakada \n tuz \n lu \n luğu \n artacak \n , \n alt \n tabakada \n yer \n alan \n hidrojen \n sülfür \n lü \n tabaka \n yükselecek \n ve \n en \n önem \n lisi \n , \n balıkların \n yaşadığı \n , \n çoğaldığı \n oksijen \n li \n üst \n tabakanın \n incelmesine \n ve \n canlı \n kaynaklarının \n yok \n olmasına \n yol \n açacaktır \n . \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n                   \n                   \n                      \n Hatta \n , \n bu \n kanal \n zaman \n içerisinde \n , \n projelendirilen \n                      \n Sinop \n                      \n nükleer \n santralini \n de \n etkileyebilecektir \n . \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n                   \n                   \n                      \n Öte \n yandan \n , \n diğer \n bir \n gerçek \n de \n                      \n Karadeniz’in \n                      \n sadece \n bize \n ait \n olmadığı \n dır \n . \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n                   \n                   \n                      \n                      \n Rusya \n                      \n , \n Montrö’den \n fayda \n sağlıyor \n . \n \n \n \n \n \n \n \n \n                   \n                   \n                      \n Ancak \n , \n yeni \n bir \n kanalın \n açılmasıyla \n birlikte \n                      \n bir \n belirsiz \n lik \n ortaya \n çıkacak \n                      \n , \n bu \n kanalın \n yetkisi \n kimde \n olacak \n ? \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n                   \n                   \n                      \n Acaba \n bu \n proje \n , \n                      \n Karadeniz \n                      \n başta \n , \n gaz \n hidrat \n ve \n petrol \n potansiyelinin \n cezbediciliğine \n yönelik \n uzun \n vade \n li \n bir \n                      \n ABD \n icadı \n anti \n Montrö \n Antlaşması \n stratejisi \n midir \n ? \n                      \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n                   \n                \n                \n                   \n                      \n Bu \n kanalla \n gelecek \n olan \n ek \n organik \n yük \n , \n denizin \n 25 \n metre \n derin \n liğinden \n sonra \n ki \n alt \n suları \n kaldırmayacak \n ve \n zaten \n kritik \n seviyede \n olan \n oksijen \n tamamen \n tükenecektir \n . \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n                   \n                \n                \n                   \n                      \n                      \n Sayın \n milletvekilleri \n                      \n , \n bir \n bilim \n insanımız \n “ \n Bu \n kanal \n , \n hava \n kir \n li \n liğine \n ve \n sağlık \n sorunlarına \n neden \n olur \n . \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n                   \n                   \n                      \n                      \n Terkos \n                      \n , \n                      \n Küçükçekmece \n                      \n ve \n                      \n Büyükçekmece \n                      \n gölleri \n kurur \n , \n                      \n Marmara \n Denizi’nde \n                      \n ki \n su \n ürünlerine \n zarar \n verir \n . \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n                   \n                   \n                      \n Kanalın \n açılması \n için \n yaklaşık \n 1 \n milyon \n metreküp \n lük \n bir \n kazıyla \n en \n az \n 42 \n kilometrekare \n lik \n                      \n yeşil \n                      \n alan \n tahrip \n edilir \n . \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n                   \n                   \n                      \n Kanalın \n etrafına \n rant \n için \n yerleşim \n bölgeleri \n inşa \n edilirse \n gemi \n kazası \n , \n patlaması \n ve \n tehlikeler \n boğazdan \n kanala \n taşınır \n . \n ” \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n                   \n                \n                Mikrofon otomatik cihaz tarafından kapatıldı \n                \n                   \n                      \n Bu \n nedenle \n , \n bunun \n gibi \n birçok \n başka \n bilimsel \n tespitlerin \n doğru \n olmadığına \n , \n yanlış \n ya \n da \n doğru \n olduğuna \n karar \n verecek \n , \n elimizde \n hiçbir \n bilimsel \n bulgu \n ve \n veri \n yok \n tur \n . \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n                   \n                   \n                      \n Bu \n nedenle \n , \n bu \n konunun \n ciddiyetle \n ele \n alınması \n ve \n bilim \n adamlarımızla \n birlikte \n konunun \n ayrıntı \n lı \n incelenmesi \n gerekiyor \n . \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n                   \n                \n                \n                   \n                      \n                      \n Yüce \n Meclisi \n                      \n saygıyla \n selamlıyorum \n .']

In [10]:
cleaned_speeches = []

for u in root.xpath(".//tei:u", namespaces=NS):
    text = " ".join(u.xpath(".//text()", namespaces=NS))
    text = clean_whitespace(text)
    if text:
        cleaned_speeches.append(text)

len(cleaned_speeches)

766

In [11]:
cleaned_speeches[:2]

['Sayın milletvekilleri , Türkiye Büyük Millet Meclisinin 109’uncu Birleşimini açıyorum . Elektronik cihazla yoklama yapacağız . Yoklama için üç dakika süre veriyorum . Elektronik cihazla yoklama yapıldı Toplantı yeter sayısı var dır , görüşmelere başlıyoruz . Gündeme geçmeden önce üç sayın milletvekiline gündem dışı söz vereceğim . Gündem dışı ilk söz , Kanal İstanbul’un çevreye etkileri hakkında söz isteyen İstanbul Milletvekili Haluk Eyidoğan’a ait tir . Buyurun Sayın Eyidoğan .',
 'Sayın Başkan , değer li milletvekilleri ; son birkaç yıldır zaman zaman gündeme gelen ve bilimsel liği çok tartışılan bir projeden bahsedeceğiz ; İstanbul’u ilgilendiren , Marmara Denizi ve Karadeniz’i ilgilendiren bir proje , ‘ Kanal İstanbul ’ . Sayın Başbakan bu projeyi ortaya attı , “ Kanal İstanbul ” dendi , bir ara çılgın projelerden biri olarak “ Çılgın Proje ” dendi . Bu projeyle ilgi li Sayın Ali Babacan şöyle diyor : “ İlk etapta bakanlar olarak ‘ Acaba olur mu , olmaz mı ? ’ ‘ Çok mu çılgın ? ’ ‘ Acaba gerçekleşebilir mi ? ’ şeklinde şüpheler hissettik ama Sayın Başbakanımız bunu açıkladı , olmayacak olsa zaten bu açıklanmazdı . ” diyor . Demek ki proje tamamen afaki , imaj projesi , hiçbir bilimsel çalışmaya dayanmıyor ; animasyon var , bilim yok . Geçenlerde cevap alamadığım ız soru önergesini burada herke sin önünde okudum , hâlâ cevap alamadık bu soru önergesine . Ama , Başbakan , bu bilimsel liği bilinmeyen projeyi Yüksek Planlama Kurulundan geçirdi . Sayın Babacan diyor ki : “ Her türlü çevre değerlendirmesi ve hazırlığı çok dikkat li yapılmalı . ” Yani anlaşılan , istim arkadan gelecek . Kanal İstanbul Projesi’nin hazırlık çalışmaları süresince , denizlerimizde yıl lardır çalışan değer li deniz bilimcilerimizin görüşü sorulmamıştır . Sayın milletvekilleri , bizim bilim insanlarımızın hesap ve modellemelerine göre , bu proje nedeniyle beklenen çevresel felaketler hem Marmara hem de Karadeniz’de olacaktır . Ben bu konuşmanın içeriğinde , yalnız denizlerimize etki açısından ele alıyorum ; bunun karada ve diğer çevre etkileri konusu ve inşaatla ilgi li konusu ayrı bir konuşma konusu dur . İstanbul Boğazı , Karadeniz’in alt tuz lu sularını Marmara’ya ulaştıran bir su yolu dur , hatta Çanakkale Boğazı yoluyla Ege’ye de gider . Nedeni , yoğun tatlı su deposu olan Karadeniz’in ortalama su seviyesinin Akdeniz’e göre daha yüksek olması dır . Karadeniz suyu Boğaz’ın üstünden akar , alt tarafından da ters yönde akan Akdeniz’in tuz lu suları Karadeniz’in tuz dengesini sağlar . Bu , eşi benzeri olmayan doğal bir akışkan lar mekanizması dır . Boğaz’ın doğal alt - üst akıntı sistemi olmasaydı , Marmara Denizi bugün künden daha beter bir açık kanalizasyona dönüşmüş olacaktı . Bu proje , Süveyş Kana lı ve Panama Kanalı’yla karşılaştırılamaz . Bu karşılaştırmayı yapmak , bilimden uzak durmak demek tir . Gerek li incelemeler yapılmadan açılacak olan bu çılgın kanalın geri dönüşü olmayacaktır . Kanalın çevreye etkileri gelecek nesiller düşünülerek incelenmelidir . Ama Planlama Kurulu karar vermiş , neye göre olduğu belli değil dir . Karadeniz’i dolduran musluklar yağmur ve nehir suları dır . Bunların başında da Tuna , Dinyeper , Dinyester ve Don nehirleri gelir . Bu havuza giren suların miktarını artırmadan Karadeniz’e bir yapay kanal açarsanız Karadeniz’in suyu daha fazla boşalır . Zaman içerisinde Karadeniz’in alt tabakada tuz lu luğu artacak , alt tabakada yer alan hidrojen sülfür lü tabaka yükselecek ve en önem lisi , balıkların yaşadığı , çoğaldığı oksijen li üst tabakanın incelmesine ve canlı kaynaklarının yok olmasına yol açacaktır . Hatta , bu kanal zaman içerisinde , projelendirilen Sinop nükleer santralini de etkileyebilecektir . Öte yandan , diğer bir gerçek de Karadeniz’in sadece bize ait olmadığı dır . Rusya , Montrö’den fayda sağlıyor . Ancak , yeni bir kanalın açılmasıyla birlikte bir belirsiz lik ortaya çıkacak , bu kanalın yetkisi kimde olacak ? Acaba bu proje , Karadeniz başta , gaz hidrat ve petrol potansiyelinin cezbediciliğine yönelik uzun vade li bir ABD icadı anti Montrö Antlaşması stratejisi midir ? Bu kanalla gelecek olan ek organik yük , denizin 25 metre derin liğinden sonra ki alt suları kaldırmayacak ve zaten kritik seviyede olan oksijen tamamen tükenecektir . Sayın milletvekilleri , bir bilim insanımız “ Bu kanal , hava kir li liğine ve sağlık sorunlarına neden olur . Terkos , Küçükçekmece ve Büyükçekmece gölleri kurur , Marmara Denizi’nde ki su ürünlerine zarar verir . Kanalın açılması için yaklaşık 1 milyon metreküp lük bir kazıyla en az 42 kilometrekare lik yeşil alan tahrip edilir . Kanalın etrafına rant için yerleşim bölgeleri inşa edilirse gemi kazası , patlaması ve tehlikeler boğazdan kanala taşınır . ” Mikrofon otomatik cihaz tarafından kapatıldı Bu nedenle , bunun gibi birçok başka bilimsel tespitlerin doğru olmadığına , yanlış ya da doğru olduğuna karar verecek , elimizde hiçbir bilimsel bulgu ve veri yok tur . Bu nedenle , bu konunun ciddiyetle ele alınması ve bilim adamlarımızla birlikte konunun ayrıntı lı incelenmesi gerekiyor . Yüce Meclisi saygıyla selamlıyorum .']

In [12]:
import pandas as pd

rows = []

In [13]:
from lxml import etree

NS = {"tei": "http://www.tei-c.org/ns/1.0"}

for file_path in tei_files:
    tree = etree.parse(file_path)
    root = tree.getroot()

    for u in root.xpath(".//tei:u", namespaces=NS):
        text = " ".join(u.xpath(".//text()", namespaces=NS))
        text = clean_whitespace(text)

        if text:
            rows.append({ "file": file_path, "speech": text})

In [14]:
df = pd.DataFrame(rows)

df.shape

(739744, 2)

In [15]:
df.head()

,file,speech
0,ParlaMint-TR.ana/ParlaMint-TR.TEI.ana/2013/Par...,"Sayın milletvekilleri , Türkiye Büyük Millet M..."
1,ParlaMint-TR.ana/ParlaMint-TR.TEI.ana/2013/Par...,"Sayın Başkan , değer li milletvekilleri ; son ..."
2,ParlaMint-TR.ana/ParlaMint-TR.TEI.ana/2013/Par...,Teşekkür ederiz Sayın Eyidoğan . Gündem dışı i...
3,ParlaMint-TR.ana/ParlaMint-TR.TEI.ana/2013/Par...,"Sayın Başkan , değer li milletvekilleri ; Türk..."
4,ParlaMint-TR.ana/ParlaMint-TR.TEI.ana/2013/Par...,Teşekkür ederiz Sayın Yeniçeri . Gündem dışı ü...

In [16]:
df["speech_lower"] = df["speech"].str.lower()

In [17]:
def contains_keywords(text, keywords):
    for kw in keywords:
        if kw in text:
            return 1
    return 0

In [18]:
for category, keywords in ENV_KEYWORDS.items():
    df[category] = df["speech_lower"].apply(
        lambda x: contains_keywords(x, keywords)
    )

In [19]:
df[ENV_KEYWORDS.keys()].sum()

extractivism             40362
energy_projects          22299
developmentalist         27079
sustainability           33328
environmental_justice     1918
dtype: int64

In [20]:
env_cols = list(ENV_KEYWORDS.keys())

df["env_speech"] = (df[env_cols].sum(axis=1) > 0).astype(int)

In [21]:
df["env_speech"].value_counts()

env_speech
0    652365
1     87379
Name: count, dtype: int64

In [22]:
# this line will show how many speeches include more than one keyword dictionary, so the overlaps. 
df[env_cols].sum(axis=1).value_counts().sort_index()

0    652365
1     60646
2     18022
3      6645
4      1969
5        97
Name: count, dtype: int64

In [23]:
df_env = df[df["env_speech"] == 1].copy()

In [24]:
df_env.shape

(87379, 9)

In [25]:
df_env[env_cols].sum().sort_values(ascending=False)

extractivism             40362
sustainability           33328
developmentalist         27079
energy_projects          22299
environmental_justice     1918
dtype: int64

In [26]:
for frame, keywords in ENV_KEYWORDS.items():
    df[frame] = df["speech_lower"].apply(lambda x: contains_keywords(x, keywords))

In [27]:
df["speech"].head()

0    Sayın milletvekilleri , Türkiye Büyük Millet M...
1    Sayın Başkan , değer li milletvekilleri ; son ...
2    Teşekkür ederiz Sayın Eyidoğan . Gündem dışı i...
3    Sayın Başkan , değer li milletvekilleri ; Türk...
4    Teşekkür ederiz Sayın Yeniçeri . Gündem dışı ü...
Name: speech, dtype: object

In [28]:
df[["speech", "env_speech"]].head()

                                              speech  env_speech
0  Sayın milletvekilleri , Türkiye Büyük Millet M...           1
1  Sayın Başkan , değer li milletvekilleri ; son ...           1
2  Teşekkür ederiz Sayın Eyidoğan . Gündem dışı i...           1
3  Sayın Başkan , değer li milletvekilleri ; Türk...           1
4  Teşekkür ederiz Sayın Yeniçeri . Gündem dışı ü...           0

In [29]:
df.columns

Index(['file', 'speech', 'speech_lower', 'extractivism', 'energy_projects',
       'developmentalist', 'sustainability', 'environmental_justice',
       'env_speech'],
      dtype='object')

In [30]:
#I realized I do not have columns of years, speaker_id etc. I could not include them. This is a big problem.

In [31]:
FRAME_COLS = [ "extractivism","energy_projects", "developmentalist", "sustainability","environmental_justice"]
df_frames = df[FRAME_COLS]

In [32]:
df_frames.head()

,extractivism,energy_projects,developmentalist,sustainability,environmental_justice
0,0,0,0,1,0
1,0,1,0,1,0
2,0,0,0,1,0
3,1,0,0,1,0
4,0,0,0,0,0

In [33]:
#we can check how much overlapping between developmentalist and other dictionaries exist
overlap_with_dev = {}

for frame in FRAME_COLS:
    if frame != "developmentalist":
        overlap_with_dev[frame] = (
            (df["developmentalist"] == 1) & (df[frame] == 1)
        ).sum()

overlap_with_dev

{'extractivism': np.int64(9173),
 'energy_projects': np.int64(5403),
 'sustainability': np.int64(7649),
 'environmental_justice': np.int64(344)}

In [34]:
speeches = []
speakers = []

for u in root.xpath(".//tei:u", namespaces=NS):
    text = " ".join(u.xpath(".//text()", namespaces=NS))
    text = clean_whitespace(text)
    
    if text:
        speeches.append(text)
        speakers.append(u.attrib.get("who"))

In [35]:
len(speeches), len(speakers)

(1172, 1172)

In [36]:
len(rows), df.shape

(739744, (739744, 9))

In [37]:
# So there is this problem that I could not add the speakers in this code although I tried multiple things, 
# In the other version that had problems in scale, was not correctly counting words butI was able to see the speakers
# but I cannot do the same in here because I am very confused at this point. 
# I asked chatgpt to solve it but it made me more confused
# Thus, this will be an incomplete version.